apiVersion: v1
kind: ConfigMap
metadata:
  name: argocd-image-updater-config
  namespace: argocd
  labels:
    app.kubernetes.io/name: argocd-image-updater
    app.kubernetes.io/part-of: argocd
    app.kubernetes.io/component: image-updater
    app.kubernetes.io/managed-by: argocd
    app.kubernetes.io/instance: argocd-image-updater
    app.kubernetes.io/version: v0.12.2
data:
  registries.conf: |
    registries:
      - name: GHCR
        api_url: https://ghcr.io
        prefix: ghcr.io
        credentials: pullsecret:argocd/ghcr-creds
  git.update-strategy: direct
  git.commit-message-template: |
    chore: update image to {{ .NewTag }} [skip ci]
