apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: hello-postgres
spec:
  instances: 3
  imageName: ghcr.io/cloudnative-pg/postgresql:15
  storage:
    size: 1Gi
    storageClass: standard
  monitoring:
    enablePodMonitor: true
